[build]
  publish = "dist/"
  command = "yarn run generate"

[context.production]
  environment = { BASE_URL = "https://relaym-api.camph.net", BASE_WEBSOCKET_URL = "wss://relaym-api.camph.net" }

[context.develop]
  environment = { BASE_URL = "https://relaym-server-dev.camph.net", BASE_WEBSOCKET_URL = "wss://relaym-server-dev.camph.net" }

[context.deploy-preview]
  environment = { BASE_URL = "https://relaym-server-dev.camph.net", BASE_WEBSOCKET_URL = "wss://relaym-server-dev.camph.net" }

[[headers]]
  for = "/_nuxt/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
